### ISSUE TITLE
The program returns [Errno 107] Transport endoint is not connected

### ISSUE THREAD

**Issue by flameshikari** [musca1997/lastfm-to-discord-status#1]
When I execute `python last.py` on Linux machine, the program return this:
```python
Now displaying your status from last.fm on discord.
Traceback (most recent call last):
  File "last.py", line 3, in <module>
    from discord_stat import discord_status
  File "/home/flameshikari/git/lastfm-to-discord-status/discord_stat.py", line 8, in <module>
    rpc_obj = rpc.DiscordIpcClient.for_platform(client_id)
  File "/home/flameshikari/git/lastfm-to-discord-status/rpc.py", line 54, in for_platform
    return UnixDiscordIpcClient(client_id)
  File "/home/flameshikari/git/lastfm-to-discord-status/rpc.py", line 46, in __init__
    self._do_handshake()
  File "/home/flameshikari/git/lastfm-to-discord-status/rpc.py", line 61, in _do_handshake
    ret_op, ret_data = self.send_recv({'v': 1, 'client_id': self.client_id}, op=OP_HANDSHAKE)
  File "/home/flameshikari/git/lastfm-to-discord-status/rpc.py", line 109, in send_recv
    self.send(data, op)
  File "/home/flameshikari/git/lastfm-to-discord-status/rpc.py", line 117, in send
    self._write(header)
  File "/home/flameshikari/git/lastfm-to-discord-status/rpc.py", line 202, in _write
    self._sock.sendall(data)
OSError: [Errno 107] Transport endpoint is not connected
FAIL: 1
```
Python version is 3.7. It works fine under Windows.

**Comment by flameshikari** [comment]
Oh, I got it. It works only on client machine with Discord turned on. I thought I could use it on server machine. No questions anymore.
